#!/bin/bash
# Wird als root vor dem Entfernen des Plugins ausgeführt.
LBHOMEDIR=${LBHOMEDIR:-/opt/loxberry}
"$LBHOMEDIR/bin/plugins/mammotion/service.sh" stop
pkill -f "bin/plugins/mammotion/mammotion_bridge.py" 2>/dev/null
exit 0
